language: python
services: memcached
sudo: false
python:
  - 2.7
  - 3.5
env:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then TOX_ENV="py27-django17"; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then TOX_ENV="py27-django18"; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then TOX_ENV="py35-django18"; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then TOX_ENV="py27-django19"; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then TOX_ENV="py35-django19"; fi
  - TOX_ENV=flake8
install:
  - pip install tox
script:
  - if [[ -e $TOX_ENV ]]; then tox -e $TOX_ENV; fi
