language: python
services: memcached
sudo: false
python:
  - 2.7
  - 3.5

matrix:
  include:
  - python: "2.7"
    env:
      - TOX_ENV=py27-django17
      - TOX_ENV=py27-django18
      - TOX_ENV=py27-django19
  - python: "3.5"
    env:
      - TOX_ENV=py35-django18
      - TOX_ENV=py35-django19

install:
  - pip install tox
script:
  - tox -e $TOX_ENV
