language: python
python:
  - "2.7"
  - "3.3"
install: pip install Django==1.6 django-classy-tags south django-wymeditor django-sekizai --use-mirrors
script: cd test_project && python manage.py test front
