language: python
services: memcached
python:
  - "2.7"
install:
  - pip install Django==1.6.1 python-memcached django-classy-tags south django-wymeditor django-sekizai six --use-mirrors
script: cd test_project && python manage.py test front